package com.megazone.ERPSystem_phase3_Monolithic.production.repository.work_performance.quality_control.QualityInspection;

public class DefectTypeRepositoryImpl implements DefectTypeRepositoryCustom{
}
