package com.megazone.ERPSystem_phase3_Monolithic.hr.repository.basic_information_management.salary;

import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Repository;

@Repository
@RequiredArgsConstructor
public class LongTermCareInsurancePensionRepositoryImpl implements LongTermCareInsurancePensionRepositoryCustom {
}
