package com.megazone.ERPSystem_phase3_Monolithic.production.repository.work_performance.goods_receipt.CompleteProduct;

public class CompleteProductRepositoryImpl implements CompleteProductRepositoryCustom{
}
