package com.megazone.ERPSystem_phase3_Monolithic.logistics.repository.inventory_management.inventory_inspection;

import com.megazone.ERPSystem_phase3_Monolithic.logistics.model.inventory_management.inventory_adjustment.InventoryInspectionDetail;
import org.springframework.data.jpa.repository.JpaRepository;

public interface InventoryInspectionDetailRepository extends JpaRepository<InventoryInspectionDetail, Long>, InventoryInspectionDetailRepositoryCustom {
}
